export const popularMovies = [
  {
    id: 436270,
    poster_path: "/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
    title: "Black Adam",
    vote_average: 7.8,
  },
  {
    id: 1013860,
    poster_path: "/g4yJTzMtOBUTAR2Qnmj8TYIcFVq.jpg",
    title: "R.I.P.D. 2: Rise of the Damned",
    vote_average: 6.1,
  },
  {
    id: 338958,
    poster_path: "/4x3pt6hoLblBeHebUa4OyiVXFiM.jpg",
    title: "Disenchanted",
    vote_average: 8.3,
  },
  {
    id: 862965,
    poster_path: "/iZvzMpREGiqDQ5eYbx8z70qPgst.jpg",
    title: "Emily the Criminal",
    vote_average: 5.6,
  },
  {
    id: 829799,
    poster_path: "/xdmmd437QdjcCls8yCQxrH5YYM4.jpg",
    title: "Paradise City",
    vote_average: 3.3,
  },
  {
    id: 988233,
    poster_path: "/xFJHb43ZAnnuiDztxZYsmyopweb.jpg",
    title: "Hex",
    vote_average: 5.9,
  },
  {
    id: 505642,
    poster_path: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    title: "Black Panther: Wakanda Forever",
    vote_average: 8.1,
  },
  {
    id: 551271,
    poster_path: "/4njdAkiBdC5LnFApeXSkFQ78GdT.jpg",
    title: "Medieval",
    vote_average: 6.5,
  },
  {
    id: 966220,
    poster_path: "/lZOODJzwuQo0etJJyBBZJOSdZcW.jpg",
    title: "Sniper: The White Raven",
    vote_average: 6.4,
  },
  {
    id: 882598,
    poster_path: "/aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg",
    title: "Smile",
    vote_average: 7.1,
  },
  {
    id: 948276,
    poster_path: "/uAeZI1JJbLPq7Bu5dziH7emHeu7.jpg",
    title: "Lost Bullet 2",
    vote_average: 7.3,
  },
  {
    id: 979924,
    poster_path: "/a14BbSHvLgzCdbDD6tAL8OBVKL1.jpg",
    title: "On the Line",
    vote_average: 4.4,
  },
  {
    id: 899294,
    poster_path: "/5NpXoAi3nEQkEgLO09nmotPfyNa.jpg",
    title: "Frank and Penelope",
    vote_average: 4.9,
  },
  {
    id: 846778,
    poster_path: "/uNzgeMetu9l4q9NDw7gtiUFwPOJ.jpg",
    title: "Margaux",
    vote_average: 6.7,
  },
  {
    id: 829280,
    poster_path: "/tegBpjM5ODoYoM1NjaiHVLEA0QM.jpg",
    title: "Enola Holmes 2",
    vote_average: 9.5,
  },
  {
    id: 872177,
    poster_path: "/9qG7cBhu444BYmcIOeoLJoCBMuO.jpg",
    title: "Corrective Measures",
    vote_average: 6.9,
  },
  {
    id: 1037858,
    poster_path: "/sWoYDNPNZs5MtzPbirXV73tIHrA.jpg",
    title: "The Soccer Football Movie",
    vote_average: 4.1,
  },
  {
    id: 676701,
    poster_path: "/jvIVl8zdNSOAJImw1elQEzxStMN.jpg",
    title: "Tad the Lost Explorer and the Curse of the Mummy",
    vote_average: 5.5,
  },
];
